FROM mcr.microsoft.com/dotnet/aspnet:7.0.1 
# Fetch latest at https://mcr.microsoft.com/v2/dotnet/aspnet/tags/list

RUN apt-get update && apt-get install -y wget curl ca-certificates gnupg \
  && echo 'deb http://apt.newrelic.com/debian/ newrelic non-free' | tee /etc/apt/sources.list.d/newrelic.list \
  && wget https://download.newrelic.com/548C16BF.gpg \
  && apt-key add 548C16BF.gpg \
  && apt-get update \
  && apt-get install -y newrelic-netcore20-agent
