name: Tibber Repo Validator

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  validation:
    uses: tibber/github-actions/.github/workflows/validate-repo.yaml@main
